// ═══════════════════════════════════════════════════════════
// PILIER_TEAMS.JS — 200 clubs du Pilier Céleste, en Maisons
// Généré : 10 divisions × 20 clubs. Chaque club appartient à une Maison ;
// deux clubs d'une même Maison ne partagent jamais une division.
// ═══════════════════════════════════════════════════════════

const PILIER_DIVISIONS = {
  gtd: {name:"Ligue du Grand Trône Divin", region:null, tier:"pro", order:0, level:"d1"},
  zenith: {name:"Ligue du Zénith", region:null, tier:"pro", order:1, level:"d2"},
  cel1: {name:"Première Ligue Céleste", region:'Le Pilier', tier:"regional", order:2, level:"d3"},
  cel2: {name:"Deuxième Ligue Céleste", region:'Le Pilier', tier:"regional", order:3, level:"r1"},
  cel3: {name:"Troisième Ligue Céleste", region:'Le Pilier', tier:"regional", order:4, level:"r2"},
  cel4: {name:"Quatrième Ligue Céleste", region:'Le Pilier', tier:"regional", order:5, level:"r3"},
  fond1: {name:"Première Ligue des Fondations", region:'Le Pilier', tier:"district", order:6, level:"dh"},
  fond2: {name:"Deuxième Ligue des Fondations", region:'Le Pilier', tier:"district", order:7, level:"dh"},
  fond3: {name:"Troisième Ligue des Fondations", region:'Le Pilier', tier:"district", order:8, level:"dh"},
  fond4: {name:"Quatrième Ligue des Fondations", region:'Le Pilier', tier:"district", order:9, level:"dh"},
};

const PILIER_TEAMS = [
  // ── Ligue du Grand Trône Divin (20 clubs) ──
  {name:"Fulgur Legio",color:'#a05050',division:'gtd',region:'Le Pilier',tier:'pro',house:"Fulgur",houseColor:'#e8d44a',branch:"Legio",level:'d1'},
  {name:"Gloria Primus",color:'#e0c040',division:'gtd',region:'Le Pilier',tier:'pro',house:"Gloria",houseColor:'#e0c040',branch:"Primus",level:'d1'},
  {name:"Luna Vigilia",color:'#6a7a8a',division:'gtd',region:'Le Pilier',tier:'pro',house:"Luna",houseColor:'#c0c0d8',branch:"Vigilia",level:'d1'},
  {name:"Lyra Primus",color:'#c0a0d0',division:'gtd',region:'Le Pilier',tier:'pro',house:"Lyra",houseColor:'#c0a0d0',branch:"Primus",level:'d1'},
  {name:"Grus Primus",color:'#b0a090',division:'gtd',region:'Le Pilier',tier:'pro',house:"Grus",houseColor:'#b0a090',branch:"Primus",level:'d1'},
  {name:"Lupus Primus",color:'#607080',division:'gtd',region:'Le Pilier',tier:'pro',house:"Lupus",houseColor:'#607080',branch:"Primus",level:'d1'},
  {name:"Terra Primus",color:'#8a7a4a',division:'gtd',region:'Le Pilier',tier:'pro',house:"Terra",houseColor:'#8a7a4a',branch:"Primus",level:'d1'},
  {name:"Orion Primus",color:'#5070c0',division:'gtd',region:'Le Pilier',tier:'pro',house:"Orion",houseColor:'#5070c0',branch:"Primus",level:'d1'},
  {name:"Vita Primus",color:'#40a060',division:'gtd',region:'Le Pilier',tier:'pro',house:"Vita",houseColor:'#40a060',branch:"Primus",level:'d1'},
  {name:"Seraph Primus",color:'#f0e0c0',division:'gtd',region:'Le Pilier',tier:'pro',house:"Seraph",houseColor:'#f0e0c0',branch:"Primus",level:'d1'},
  {name:"Cygnus Primus",color:'#d0d0e0',division:'gtd',region:'Le Pilier',tier:'pro',house:"Cygnus",houseColor:'#d0d0e0',branch:"Primus",level:'d1'},
  {name:"Corvus Primus",color:'#404050',division:'gtd',region:'Le Pilier',tier:'pro',house:"Corvus",houseColor:'#404050',branch:"Primus",level:'d1'},
  {name:"Ferox Primus",color:'#a04030',division:'gtd',region:'Le Pilier',tier:'pro',house:"Ferox",houseColor:'#a04030',branch:"Primus",level:'d1'},
  {name:"Tenebris Primus",color:'#302040',division:'gtd',region:'Le Pilier',tier:'pro',house:"Tenebris",houseColor:'#302040',branch:"Primus",level:'d1'},
  {name:"Nox Primus",color:'#4a4a6a',division:'gtd',region:'Le Pilier',tier:'pro',house:"Nox",houseColor:'#4a4a6a',branch:"Primus",level:'d1'},
  {name:"Abyssus Primus",color:'#3a2a4a',division:'gtd',region:'Le Pilier',tier:'pro',house:"Abyssus",houseColor:'#3a2a4a',branch:"Primus",level:'d1'},
  {name:"Lux Primus",color:'#f5e6a0',division:'gtd',region:'Le Pilier',tier:'pro',house:"Lux",houseColor:'#f5e6a0',branch:"Primus",level:'d1'},
  {name:"Serpens Primus",color:'#409060',division:'gtd',region:'Le Pilier',tier:'pro',house:"Serpens",houseColor:'#409060',branch:"Primus",level:'d1'},
  {name:"Mortis Primus",color:'#503050',division:'gtd',region:'Le Pilier',tier:'pro',house:"Mortis",houseColor:'#503050',branch:"Primus",level:'d1'},
  {name:"Draco Excelsior",color:'#e8d48a',division:'gtd',region:'Le Pilier',tier:'pro',house:"Draco",houseColor:'#307050',branch:"Excelsior",level:'d1'},
  // ── Ligue du Zénith (20 clubs) ──
  {name:"Infernus Primus",color:'#c03020',division:'zenith',region:'Le Pilier',tier:'pro',house:"Infernus",houseColor:'#c03020',branch:"Primus",level:'d2'},
  {name:"Vulpes Excelsior",color:'#e8d48a',division:'zenith',region:'Le Pilier',tier:'pro',house:"Vulpes",houseColor:'#c07040',branch:"Excelsior",level:'d2'},
  {name:"Ignis Primus",color:'#e0502f',division:'zenith',region:'Le Pilier',tier:'pro',house:"Ignis",houseColor:'#e0502f',branch:"Primus",level:'d2'},
  {name:"Fulgur Primus",color:'#e8d44a',division:'zenith',region:'Le Pilier',tier:'pro',house:"Fulgur",houseColor:'#e8d44a',branch:"Primus",level:'d2'},
  {name:"Pavo Primus",color:'#3060a0',division:'zenith',region:'Le Pilier',tier:'pro',house:"Pavo",houseColor:'#3060a0',branch:"Primus",level:'d2'},
  {name:"Umbra Primus",color:'#6a4a8a',division:'zenith',region:'Le Pilier',tier:'pro',house:"Umbra",houseColor:'#6a4a8a',branch:"Primus",level:'d2'},
  {name:"Ferox Excelsior",color:'#e8d48a',division:'zenith',region:'Le Pilier',tier:'pro',house:"Ferox",houseColor:'#a04030',branch:"Excelsior",level:'d2'},
  {name:"Hydra Primus",color:'#308070',division:'zenith',region:'Le Pilier',tier:'pro',house:"Hydra",houseColor:'#308070',branch:"Primus",level:'d2'},
  {name:"Phoenix Primus",color:'#e06020',division:'zenith',region:'Le Pilier',tier:'pro',house:"Phoenix",houseColor:'#e06020',branch:"Primus",level:'d2'},
  {name:"Astra Primus",color:'#c0a0e0',division:'zenith',region:'Le Pilier',tier:'pro',house:"Astra",houseColor:'#c0a0e0',branch:"Primus",level:'d2'},
  {name:"Aurora Primus",color:'#e88ab0',division:'zenith',region:'Le Pilier',tier:'pro',house:"Aurora",houseColor:'#e88ab0',branch:"Primus",level:'d2'},
  {name:"Lyra Excelsior",color:'#e8d48a',division:'zenith',region:'Le Pilier',tier:'pro',house:"Lyra",houseColor:'#c0a0d0',branch:"Excelsior",level:'d2'},
  {name:"Ventus Primus",color:'#7ec8e3',division:'zenith',region:'Le Pilier',tier:'pro',house:"Ventus",houseColor:'#7ec8e3',branch:"Primus",level:'d2'},
  {name:"Aquila Primus",color:'#b08040',division:'zenith',region:'Le Pilier',tier:'pro',house:"Aquila",houseColor:'#b08040',branch:"Primus",level:'d2'},
  {name:"Aqua Primus",color:'#3a9ad0',division:'zenith',region:'Le Pilier',tier:'pro',house:"Aqua",houseColor:'#3a9ad0',branch:"Primus",level:'d2'},
  {name:"Luna Primus",color:'#c0c0d8',division:'zenith',region:'Le Pilier',tier:'pro',house:"Luna",houseColor:'#c0c0d8',branch:"Primus",level:'d2'},
  {name:"Caelum Primus",color:'#a0d0f0',division:'zenith',region:'Le Pilier',tier:'pro',house:"Caelum",houseColor:'#a0d0f0',branch:"Primus",level:'d2'},
  {name:"Gloria Excelsior",color:'#e8d48a',division:'zenith',region:'Le Pilier',tier:'pro',house:"Gloria",houseColor:'#e0c040',branch:"Excelsior",level:'d2'},
  {name:"Aether Primus",color:'#d4af37',division:'zenith',region:'Le Pilier',tier:'pro',house:"Aether",houseColor:'#d4af37',branch:"Primus",level:'d2'},
  {name:"Gehenna Primus",color:'#7a2020',division:'zenith',region:'Le Pilier',tier:'pro',house:"Gehenna",houseColor:'#7a2020',branch:"Primus",level:'d2'},
  // ── Première Ligue Céleste (20 clubs) ──
  {name:"Draco Primus",color:'#307050',division:'cel1',region:'Le Pilier',tier:'regional',house:"Draco",houseColor:'#307050',branch:"Primus",level:'d3'},
  {name:"Gloria Secundus",color:'#e0c040',division:'cel1',region:'Le Pilier',tier:'regional',house:"Gloria",houseColor:'#e0c040',branch:"Secundus",level:'d3'},
  {name:"Ursa Secundus",color:'#705040',division:'cel1',region:'Le Pilier',tier:'regional',house:"Ursa",houseColor:'#705040',branch:"Secundus",level:'d3'},
  {name:"Hydra Secundus",color:'#308070',division:'cel1',region:'Le Pilier',tier:'regional',house:"Hydra",houseColor:'#308070',branch:"Secundus",level:'d3'},
  {name:"Sol Primus",color:'#f0a020',division:'cel1',region:'Le Pilier',tier:'regional',house:"Sol",houseColor:'#f0a020',branch:"Primus",level:'d3'},
  {name:"Umbra Secundus",color:'#6a4a8a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Umbra",houseColor:'#6a4a8a',branch:"Secundus",level:'d3'},
  {name:"Lupus Excelsior",color:'#e8d48a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Lupus",houseColor:'#607080',branch:"Excelsior",level:'d3'},
  {name:"Ferox Secundus",color:'#a04030',division:'cel1',region:'Le Pilier',tier:'regional',house:"Ferox",houseColor:'#a04030',branch:"Secundus",level:'d3'},
  {name:"Infernus Excelsior",color:'#e8d48a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Infernus",houseColor:'#c03020',branch:"Excelsior",level:'d3'},
  {name:"Orion Secundus",color:'#5070c0',division:'cel1',region:'Le Pilier',tier:'regional',house:"Orion",houseColor:'#5070c0',branch:"Secundus",level:'d3'},
  {name:"Vulpes Primus",color:'#c07040',division:'cel1',region:'Le Pilier',tier:'regional',house:"Vulpes",houseColor:'#c07040',branch:"Primus",level:'d3'},
  {name:"Seraph Excelsior",color:'#e8d48a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Seraph",houseColor:'#f0e0c0',branch:"Excelsior",level:'d3'},
  {name:"Pavo Secundus",color:'#3060a0',division:'cel1',region:'Le Pilier',tier:'regional',house:"Pavo",houseColor:'#3060a0',branch:"Secundus",level:'d3'},
  {name:"Aqua Excelsior",color:'#e8d48a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Aqua",houseColor:'#3a9ad0',branch:"Excelsior",level:'d3'},
  {name:"Sanctus Primus",color:'#e8e0d0',division:'cel1',region:'Le Pilier',tier:'regional',house:"Sanctus",houseColor:'#e8e0d0',branch:"Primus",level:'d3'},
  {name:"Aquila Excelsior",color:'#e8d48a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Aquila",houseColor:'#b08040',branch:"Excelsior",level:'d3'},
  {name:"Corvus Excelsior",color:'#e8d48a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Corvus",houseColor:'#404050',branch:"Excelsior",level:'d3'},
  {name:"Terra Secundus",color:'#8a7a4a',division:'cel1',region:'Le Pilier',tier:'regional',house:"Terra",houseColor:'#8a7a4a',branch:"Secundus",level:'d3'},
  {name:"Fulgur Custodes",color:'#8a9ba8',division:'cel1',region:'Le Pilier',tier:'regional',house:"Fulgur",houseColor:'#e8d44a',branch:"Custodes",level:'d3'},
  {name:"Ignis Secundus",color:'#e0502f',division:'cel1',region:'Le Pilier',tier:'regional',house:"Ignis",houseColor:'#e0502f',branch:"Secundus",level:'d3'},
  // ── Deuxième Ligue Céleste (20 clubs) ──
  {name:"Hydra Excelsior",color:'#e8d48a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Hydra",houseColor:'#308070',branch:"Excelsior",level:'r1'},
  {name:"Grus Excelsior",color:'#e8d48a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Grus",houseColor:'#b0a090',branch:"Excelsior",level:'r1'},
  {name:"Gehenna Ordo",color:'#c0a060',division:'cel2',region:'Le Pilier',tier:'regional',house:"Gehenna",houseColor:'#7a2020',branch:"Ordo",level:'r1'},
  {name:"Leo Custodes",color:'#8a9ba8',division:'cel2',region:'Le Pilier',tier:'regional',house:"Leo",houseColor:'#d0a030',branch:"Custodes",level:'r1'},
  {name:"Lyra Ordo",color:'#c0a060',division:'cel2',region:'Le Pilier',tier:'regional',house:"Lyra",houseColor:'#c0a0d0',branch:"Ordo",level:'r1'},
  {name:"Serpens Ordo",color:'#c0a060',division:'cel2',region:'Le Pilier',tier:'regional',house:"Serpens",houseColor:'#409060',branch:"Ordo",level:'r1'},
  {name:"Orion Excelsior",color:'#e8d48a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Orion",houseColor:'#5070c0',branch:"Excelsior",level:'r1'},
  {name:"Lux Excelsior",color:'#e8d48a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Lux",houseColor:'#f5e6a0',branch:"Excelsior",level:'r1'},
  {name:"Vulpes Secundus",color:'#c07040',division:'cel2',region:'Le Pilier',tier:'regional',house:"Vulpes",houseColor:'#c07040',branch:"Secundus",level:'r1'},
  {name:"Sol Excelsior",color:'#e8d48a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Sol",houseColor:'#f0a020',branch:"Excelsior",level:'r1'},
  {name:"Aurora Excelsior",color:'#e8d48a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Aurora",houseColor:'#e88ab0',branch:"Excelsior",level:'r1'},
  {name:"Abyssus Secundus",color:'#3a2a4a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Abyssus",houseColor:'#3a2a4a',branch:"Secundus",level:'r1'},
  {name:"Seraph Secundus",color:'#f0e0c0',division:'cel2',region:'Le Pilier',tier:'regional',house:"Seraph",houseColor:'#f0e0c0',branch:"Secundus",level:'r1'},
  {name:"Aqua Secundus",color:'#3a9ad0',division:'cel2',region:'Le Pilier',tier:'regional',house:"Aqua",houseColor:'#3a9ad0',branch:"Secundus",level:'r1'},
  {name:"Ignis Custodes",color:'#8a9ba8',division:'cel2',region:'Le Pilier',tier:'regional',house:"Ignis",houseColor:'#e0502f',branch:"Custodes",level:'r1'},
  {name:"Gloria Academia",color:'#7ec8e3',division:'cel2',region:'Le Pilier',tier:'regional',house:"Gloria",houseColor:'#e0c040',branch:"Academia",level:'r1'},
  {name:"Taurus Custodes",color:'#8a9ba8',division:'cel2',region:'Le Pilier',tier:'regional',house:"Taurus",houseColor:'#906040',branch:"Custodes",level:'r1'},
  {name:"Umbra Ordo",color:'#c0a060',division:'cel2',region:'Le Pilier',tier:'regional',house:"Umbra",houseColor:'#6a4a8a',branch:"Ordo",level:'r1'},
  {name:"Aquila Secundus",color:'#b08040',division:'cel2',region:'Le Pilier',tier:'regional',house:"Aquila",houseColor:'#b08040',branch:"Secundus",level:'r1'},
  {name:"Tenebris Mercatoria",color:'#c8a84a',division:'cel2',region:'Le Pilier',tier:'regional',house:"Tenebris",houseColor:'#302040',branch:"Mercatoria",level:'r1'},
  // ── Troisième Ligue Céleste (20 clubs) ──
  {name:"Gloria Mercatoria",color:'#c8a84a',division:'cel3',region:'Le Pilier',tier:'regional',house:"Gloria",houseColor:'#e0c040',branch:"Mercatoria",level:'r2'},
  {name:"Ursa Nova",color:'#9ad8b0',division:'cel3',region:'Le Pilier',tier:'regional',house:"Ursa",houseColor:'#705040',branch:"Nova",level:'r2'},
  {name:"Terra Mercatoria",color:'#c8a84a',division:'cel3',region:'Le Pilier',tier:'regional',house:"Terra",houseColor:'#8a7a4a',branch:"Mercatoria",level:'r2'},
  {name:"Aurora Nova",color:'#9ad8b0',division:'cel3',region:'Le Pilier',tier:'regional',house:"Aurora",houseColor:'#e88ab0',branch:"Nova",level:'r2'},
  {name:"Pavo Ordo",color:'#c0a060',division:'cel3',region:'Le Pilier',tier:'regional',house:"Pavo",houseColor:'#3060a0',branch:"Ordo",level:'r2'},
  {name:"Vita Custodes",color:'#8a9ba8',division:'cel3',region:'Le Pilier',tier:'regional',house:"Vita",houseColor:'#40a060',branch:"Custodes",level:'r2'},
  {name:"Luna Ordo",color:'#c0a060',division:'cel3',region:'Le Pilier',tier:'regional',house:"Luna",houseColor:'#c0c0d8',branch:"Ordo",level:'r2'},
  {name:"Serpens Mercatoria",color:'#c8a84a',division:'cel3',region:'Le Pilier',tier:'regional',house:"Serpens",houseColor:'#409060',branch:"Mercatoria",level:'r2'},
  {name:"Taurus Academia",color:'#7ec8e3',division:'cel3',region:'Le Pilier',tier:'regional',house:"Taurus",houseColor:'#906040',branch:"Academia",level:'r2'},
  {name:"Sol Academia",color:'#7ec8e3',division:'cel3',region:'Le Pilier',tier:'regional',house:"Sol",houseColor:'#f0a020',branch:"Academia",level:'r2'},
  {name:"Tenebris Custodes",color:'#8a9ba8',division:'cel3',region:'Le Pilier',tier:'regional',house:"Tenebris",houseColor:'#302040',branch:"Custodes",level:'r2'},
  {name:"Draco Secundus",color:'#307050',division:'cel3',region:'Le Pilier',tier:'regional',house:"Draco",houseColor:'#307050',branch:"Secundus",level:'r2'},
  {name:"Nox Custodes",color:'#8a9ba8',division:'cel3',region:'Le Pilier',tier:'regional',house:"Nox",houseColor:'#4a4a6a',branch:"Custodes",level:'r2'},
  {name:"Caelum Custodes",color:'#8a9ba8',division:'cel3',region:'Le Pilier',tier:'regional',house:"Caelum",houseColor:'#a0d0f0',branch:"Custodes",level:'r2'},
  {name:"Ventus Academia",color:'#7ec8e3',division:'cel3',region:'Le Pilier',tier:'regional',house:"Ventus",houseColor:'#7ec8e3',branch:"Academia",level:'r2'},
  {name:"Ignis Nova",color:'#9ad8b0',division:'cel3',region:'Le Pilier',tier:'regional',house:"Ignis",houseColor:'#e0502f',branch:"Nova",level:'r2'},
  {name:"Sanctus Mercatoria",color:'#c8a84a',division:'cel3',region:'Le Pilier',tier:'regional',house:"Sanctus",houseColor:'#e8e0d0',branch:"Mercatoria",level:'r2'},
  {name:"Fulgur Secundus",color:'#e8d44a',division:'cel3',region:'Le Pilier',tier:'regional',house:"Fulgur",houseColor:'#e8d44a',branch:"Secundus",level:'r2'},
  {name:"Corvus Custodes",color:'#8a9ba8',division:'cel3',region:'Le Pilier',tier:'regional',house:"Corvus",houseColor:'#404050',branch:"Custodes",level:'r2'},
  {name:"Mortis Academia",color:'#7ec8e3',division:'cel3',region:'Le Pilier',tier:'regional',house:"Mortis",houseColor:'#503050',branch:"Academia",level:'r2'},
  // ── Quatrième Ligue Céleste (20 clubs) ──
  {name:"Aether Custodes",color:'#8a9ba8',division:'cel4',region:'Le Pilier',tier:'regional',house:"Aether",houseColor:'#d4af37',branch:"Custodes",level:'r3'},
  {name:"Fulgur Vigilia",color:'#6a7a8a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Fulgur",houseColor:'#e8d44a',branch:"Vigilia",level:'r3'},
  {name:"Ferox Academia",color:'#7ec8e3',division:'cel4',region:'Le Pilier',tier:'regional',house:"Ferox",houseColor:'#a04030',branch:"Academia",level:'r3'},
  {name:"Sanctus Vigilia",color:'#6a7a8a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Sanctus",houseColor:'#e8e0d0',branch:"Vigilia",level:'r3'},
  {name:"Astra Sanctum",color:'#d8c8e8',division:'cel4',region:'Le Pilier',tier:'regional',house:"Astra",houseColor:'#c0a0e0',branch:"Sanctum",level:'r3'},
  {name:"Sol Ordo",color:'#c0a060',division:'cel4',region:'Le Pilier',tier:'regional',house:"Sol",houseColor:'#f0a020',branch:"Ordo",level:'r3'},
  {name:"Phoenix Mercatoria",color:'#c8a84a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Phoenix",houseColor:'#e06020',branch:"Mercatoria",level:'r3'},
  {name:"Corvus Vigilia",color:'#6a7a8a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Corvus",houseColor:'#404050',branch:"Vigilia",level:'r3'},
  {name:"Orion Nova",color:'#9ad8b0',division:'cel4',region:'Le Pilier',tier:'regional',house:"Orion",houseColor:'#5070c0',branch:"Nova",level:'r3'},
  {name:"Pavo Mercatoria",color:'#c8a84a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Pavo",houseColor:'#3060a0',branch:"Mercatoria",level:'r3'},
  {name:"Aqua Sanctum",color:'#d8c8e8',division:'cel4',region:'Le Pilier',tier:'regional',house:"Aqua",houseColor:'#3a9ad0',branch:"Sanctum",level:'r3'},
  {name:"Caelum Ferrum",color:'#8a7a5a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Caelum",houseColor:'#a0d0f0',branch:"Ferrum",level:'r3'},
  {name:"Ventus Custodes",color:'#8a9ba8',division:'cel4',region:'Le Pilier',tier:'regional',house:"Ventus",houseColor:'#7ec8e3',branch:"Custodes",level:'r3'},
  {name:"Nox Nova #16",color:'#9ad8b0',division:'cel4',region:'Le Pilier',tier:'regional',house:"Nox",houseColor:'#4a4a6a',branch:"Nova",level:'r3'},
  {name:"Infernus Nova #24",color:'#9ad8b0',division:'cel4',region:'Le Pilier',tier:'regional',house:"Infernus",houseColor:'#c03020',branch:"Nova",level:'r3'},
  {name:"Draco Vigilia",color:'#6a7a8a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Draco",houseColor:'#307050',branch:"Vigilia",level:'r3'},
  {name:"Ursa Nova #14",color:'#9ad8b0',division:'cel4',region:'Le Pilier',tier:'regional',house:"Ursa",houseColor:'#705040',branch:"Nova",level:'r3'},
  {name:"Cygnus Vigilia",color:'#6a7a8a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Cygnus",houseColor:'#d0d0e0',branch:"Vigilia",level:'r3'},
  {name:"Lux Vigilia",color:'#6a7a8a',division:'cel4',region:'Le Pilier',tier:'regional',house:"Lux",houseColor:'#f5e6a0',branch:"Vigilia",level:'r3'},
  {name:"Mortis Ordo",color:'#c0a060',division:'cel4',region:'Le Pilier',tier:'regional',house:"Mortis",houseColor:'#503050',branch:"Ordo",level:'r3'},
  // ── Première Ligue des Fondations (20 clubs) ──
  {name:"Astra Nova V",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Astra",houseColor:'#c0a0e0',branch:"Nova",level:'dh'},
  {name:"Aurora Mercatoria",color:'#c8a84a',division:'fond1',region:'Le Pilier',tier:'district',house:"Aurora",houseColor:'#e88ab0',branch:"Mercatoria",level:'dh'},
  {name:"Seraph Vigilia",color:'#6a7a8a',division:'fond1',region:'Le Pilier',tier:'district',house:"Seraph",houseColor:'#f0e0c0',branch:"Vigilia",level:'dh'},
  {name:"Grus Academia",color:'#7ec8e3',division:'fond1',region:'Le Pilier',tier:'district',house:"Grus",houseColor:'#b0a090',branch:"Academia",level:'dh'},
  {name:"Abyssus Vigilia",color:'#6a7a8a',division:'fond1',region:'Le Pilier',tier:'district',house:"Abyssus",houseColor:'#3a2a4a',branch:"Vigilia",level:'dh'},
  {name:"Caelum Nova #22",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Caelum",houseColor:'#a0d0f0',branch:"Nova",level:'dh'},
  {name:"Aquila Academia",color:'#7ec8e3',division:'fond1',region:'Le Pilier',tier:'district',house:"Aquila",houseColor:'#b08040',branch:"Academia",level:'dh'},
  {name:"Leo Vigilia",color:'#6a7a8a',division:'fond1',region:'Le Pilier',tier:'district',house:"Leo",houseColor:'#d0a030',branch:"Vigilia",level:'dh'},
  {name:"Taurus Nova #27",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Taurus",houseColor:'#906040',branch:"Nova",level:'dh'},
  {name:"Ferox Vigilia",color:'#6a7a8a',division:'fond1',region:'Le Pilier',tier:'district',house:"Ferox",houseColor:'#a04030',branch:"Vigilia",level:'dh'},
  {name:"Lupus Mercatoria",color:'#c8a84a',division:'fond1',region:'Le Pilier',tier:'district',house:"Lupus",houseColor:'#607080',branch:"Mercatoria",level:'dh'},
  {name:"Vulpes Legio",color:'#a05050',division:'fond1',region:'Le Pilier',tier:'district',house:"Vulpes",houseColor:'#c07040',branch:"Legio",level:'dh'},
  {name:"Tenebris Nova #11",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Tenebris",houseColor:'#302040',branch:"Nova",level:'dh'},
  {name:"Sol Sanctum",color:'#d8c8e8',division:'fond1',region:'Le Pilier',tier:'district',house:"Sol",houseColor:'#f0a020',branch:"Sanctum",level:'dh'},
  {name:"Sanctus Nova II",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Sanctus",houseColor:'#e8e0d0',branch:"Nova",level:'dh'},
  {name:"Nox Nova #8",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Nox",houseColor:'#4a4a6a',branch:"Nova",level:'dh'},
  {name:"Lyra Academia",color:'#7ec8e3',division:'fond1',region:'Le Pilier',tier:'district',house:"Lyra",houseColor:'#c0a0d0',branch:"Academia",level:'dh'},
  {name:"Orion Nova #21",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Orion",houseColor:'#5070c0',branch:"Nova",level:'dh'},
  {name:"Corvus Nova #25",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Corvus",houseColor:'#404050',branch:"Nova",level:'dh'},
  {name:"Gehenna Nova",color:'#9ad8b0',division:'fond1',region:'Le Pilier',tier:'district',house:"Gehenna",houseColor:'#7a2020',branch:"Nova",level:'dh'},
  // ── Deuxième Ligue des Fondations (20 clubs) ──
  {name:"Fulgur Sanctum",color:'#d8c8e8',division:'fond2',region:'Le Pilier',tier:'district',house:"Fulgur",houseColor:'#e8d44a',branch:"Sanctum",level:'dh'},
  {name:"Mortis Vigilia",color:'#6a7a8a',division:'fond2',region:'Le Pilier',tier:'district',house:"Mortis",houseColor:'#503050',branch:"Vigilia",level:'dh'},
  {name:"Ignis Nova #15",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Ignis",houseColor:'#e0502f',branch:"Nova",level:'dh'},
  {name:"Serpens Nova #23",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Serpens",houseColor:'#409060',branch:"Nova",level:'dh'},
  {name:"Sol Ferrum",color:'#8a7a5a',division:'fond2',region:'Le Pilier',tier:'district',house:"Sol",houseColor:'#f0a020',branch:"Ferrum",level:'dh'},
  {name:"Lyra Nova #20",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Lyra",houseColor:'#c0a0d0',branch:"Nova",level:'dh'},
  {name:"Astra Vigilia",color:'#6a7a8a',division:'fond2',region:'Le Pilier',tier:'district',house:"Astra",houseColor:'#c0a0e0',branch:"Vigilia",level:'dh'},
  {name:"Abyssus Nova VI",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Abyssus",houseColor:'#3a2a4a',branch:"Nova",level:'dh'},
  {name:"Leo Sanctum",color:'#d8c8e8',division:'fond2',region:'Le Pilier',tier:'district',house:"Leo",houseColor:'#d0a030',branch:"Sanctum",level:'dh'},
  {name:"Umbra Nova #10",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Umbra",houseColor:'#6a4a8a',branch:"Nova",level:'dh'},
  {name:"Lux Sanctum",color:'#d8c8e8',division:'fond2',region:'Le Pilier',tier:'district',house:"Lux",houseColor:'#f5e6a0',branch:"Sanctum",level:'dh'},
  {name:"Infernus Ferrum",color:'#8a7a5a',division:'fond2',region:'Le Pilier',tier:'district',house:"Infernus",houseColor:'#c03020',branch:"Ferrum",level:'dh'},
  {name:"Nox Nova #9",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Nox",houseColor:'#4a4a6a',branch:"Nova",level:'dh'},
  {name:"Phoenix Nova VII",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Phoenix",houseColor:'#e06020',branch:"Nova",level:'dh'},
  {name:"Orion Nova #12",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Orion",houseColor:'#5070c0',branch:"Nova",level:'dh'},
  {name:"Sanctus Ferrum",color:'#8a7a5a',division:'fond2',region:'Le Pilier',tier:'district',house:"Sanctus",houseColor:'#e8e0d0',branch:"Ferrum",level:'dh'},
  {name:"Ursa Vigilia",color:'#6a7a8a',division:'fond2',region:'Le Pilier',tier:'district',house:"Ursa",houseColor:'#705040',branch:"Vigilia",level:'dh'},
  {name:"Vita Nova",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Vita",houseColor:'#40a060',branch:"Nova",level:'dh'},
  {name:"Ventus Nova #28",color:'#9ad8b0',division:'fond2',region:'Le Pilier',tier:'district',house:"Ventus",houseColor:'#7ec8e3',branch:"Nova",level:'dh'},
  {name:"Vulpes Sanctum",color:'#d8c8e8',division:'fond2',region:'Le Pilier',tier:'district',house:"Vulpes",houseColor:'#c07040',branch:"Sanctum",level:'dh'},
  // ── Troisième Ligue des Fondations (20 clubs) ──
  {name:"Fulgur Nova #26",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Fulgur",houseColor:'#e8d44a',branch:"Nova",level:'dh'},
  {name:"Ignis Vigilia",color:'#6a7a8a',division:'fond3',region:'Le Pilier',tier:'district',house:"Ignis",houseColor:'#e0502f',branch:"Vigilia",level:'dh'},
  {name:"Serpens Nova III",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Serpens",houseColor:'#409060',branch:"Nova",level:'dh'},
  {name:"Lyra Vigilia",color:'#6a7a8a',division:'fond3',region:'Le Pilier',tier:'district',house:"Lyra",houseColor:'#c0a0d0',branch:"Vigilia",level:'dh'},
  {name:"Tenebris Ferrum",color:'#8a7a5a',division:'fond3',region:'Le Pilier',tier:'district',house:"Tenebris",houseColor:'#302040',branch:"Ferrum",level:'dh'},
  {name:"Umbra Sanctum",color:'#d8c8e8',division:'fond3',region:'Le Pilier',tier:'district',house:"Umbra",houseColor:'#6a4a8a',branch:"Sanctum",level:'dh'},
  {name:"Pavo Nova #17",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Pavo",houseColor:'#3060a0',branch:"Nova",level:'dh'},
  {name:"Phoenix Vigilia",color:'#6a7a8a',division:'fond3',region:'Le Pilier',tier:'district',house:"Phoenix",houseColor:'#e06020',branch:"Vigilia",level:'dh'},
  {name:"Lupus Nova #13",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Lupus",houseColor:'#607080',branch:"Nova",level:'dh'},
  {name:"Nox Vigilia",color:'#6a7a8a',division:'fond3',region:'Le Pilier',tier:'district',house:"Nox",houseColor:'#4a4a6a',branch:"Vigilia",level:'dh'},
  {name:"Ursa Sanctum",color:'#d8c8e8',division:'fond3',region:'Le Pilier',tier:'district',house:"Ursa",houseColor:'#705040',branch:"Sanctum",level:'dh'},
  {name:"Seraph Legio",color:'#a05050',division:'fond3',region:'Le Pilier',tier:'district',house:"Seraph",houseColor:'#f0e0c0',branch:"Legio",level:'dh'},
  {name:"Aquila Nova",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Aquila",houseColor:'#b08040',branch:"Nova",level:'dh'},
  {name:"Grus Ferrum",color:'#8a7a5a',division:'fond3',region:'Le Pilier',tier:'district',house:"Grus",houseColor:'#b0a090',branch:"Ferrum",level:'dh'},
  {name:"Draco Mercatoria",color:'#c8a84a',division:'fond3',region:'Le Pilier',tier:'district',house:"Draco",houseColor:'#307050',branch:"Mercatoria",level:'dh'},
  {name:"Aether Ordo",color:'#c0a060',division:'fond3',region:'Le Pilier',tier:'district',house:"Aether",houseColor:'#d4af37',branch:"Ordo",level:'dh'},
  {name:"Hydra Ferrum",color:'#8a7a5a',division:'fond3',region:'Le Pilier',tier:'district',house:"Hydra",houseColor:'#308070',branch:"Ferrum",level:'dh'},
  {name:"Infernus Nova IV",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Infernus",houseColor:'#c03020',branch:"Nova",level:'dh'},
  {name:"Ventus Nova",color:'#9ad8b0',division:'fond3',region:'Le Pilier',tier:'district',house:"Ventus",houseColor:'#7ec8e3',branch:"Nova",level:'dh'},
  {name:"Ferox Mercatoria",color:'#c8a84a',division:'fond3',region:'Le Pilier',tier:'district',house:"Ferox",houseColor:'#a04030',branch:"Mercatoria",level:'dh'},
  // ── Quatrième Ligue des Fondations (20 clubs) ──
  {name:"Ignis Sanctum",color:'#d8c8e8',division:'fond4',region:'Le Pilier',tier:'district',house:"Ignis",houseColor:'#e0502f',branch:"Sanctum",level:'dh'},
  {name:"Serpens Sanctum",color:'#d8c8e8',division:'fond4',region:'Le Pilier',tier:'district',house:"Serpens",houseColor:'#409060',branch:"Sanctum",level:'dh'},
  {name:"Pavo Nova",color:'#9ad8b0',division:'fond4',region:'Le Pilier',tier:'district',house:"Pavo",houseColor:'#3060a0',branch:"Nova",level:'dh'},
  {name:"Phoenix Ferrum",color:'#8a7a5a',division:'fond4',region:'Le Pilier',tier:'district',house:"Phoenix",houseColor:'#e06020',branch:"Ferrum",level:'dh'},
  {name:"Vulpes Mercatoria",color:'#c8a84a',division:'fond4',region:'Le Pilier',tier:'district',house:"Vulpes",houseColor:'#c07040',branch:"Mercatoria",level:'dh'},
  {name:"Astra Academia",color:'#7ec8e3',division:'fond4',region:'Le Pilier',tier:'district',house:"Astra",houseColor:'#c0a0e0',branch:"Academia",level:'dh'},
  {name:"Aether Vigilia",color:'#6a7a8a',division:'fond4',region:'Le Pilier',tier:'district',house:"Aether",houseColor:'#d4af37',branch:"Vigilia",level:'dh'},
  {name:"Lyra Custodes",color:'#8a9ba8',division:'fond4',region:'Le Pilier',tier:'district',house:"Lyra",houseColor:'#c0a0d0',branch:"Custodes",level:'dh'},
  {name:"Gehenna Nova #19",color:'#9ad8b0',division:'fond4',region:'Le Pilier',tier:'district',house:"Gehenna",houseColor:'#7a2020',branch:"Nova",level:'dh'},
  {name:"Taurus Primus",color:'#906040',division:'fond4',region:'Le Pilier',tier:'district',house:"Taurus",houseColor:'#906040',branch:"Primus",level:'dh'},
  {name:"Draco Ferrum",color:'#8a7a5a',division:'fond4',region:'Le Pilier',tier:'district',house:"Draco",houseColor:'#307050',branch:"Ferrum",level:'dh'},
  {name:"Ursa Primus",color:'#705040',division:'fond4',region:'Le Pilier',tier:'district',house:"Ursa",houseColor:'#705040',branch:"Primus",level:'dh'},
  {name:"Leo Primus",color:'#d0a030',division:'fond4',region:'Le Pilier',tier:'district',house:"Leo",houseColor:'#d0a030',branch:"Primus",level:'dh'},
  {name:"Cygnus Ordo",color:'#c0a060',division:'fond4',region:'Le Pilier',tier:'district',house:"Cygnus",houseColor:'#d0d0e0',branch:"Ordo",level:'dh'},
  {name:"Caelum Academia",color:'#7ec8e3',division:'fond4',region:'Le Pilier',tier:'district',house:"Caelum",houseColor:'#a0d0f0',branch:"Academia",level:'dh'},
  {name:"Aurora Secundus",color:'#e88ab0',division:'fond4',region:'Le Pilier',tier:'district',house:"Aurora",houseColor:'#e88ab0',branch:"Secundus",level:'dh'},
  {name:"Lupus Secundus",color:'#607080',division:'fond4',region:'Le Pilier',tier:'district',house:"Lupus",houseColor:'#607080',branch:"Secundus",level:'dh'},
  {name:"Fulgur Nova #18",color:'#9ad8b0',division:'fond4',region:'Le Pilier',tier:'district',house:"Fulgur",houseColor:'#e8d44a',branch:"Nova",level:'dh'},
  {name:"Luna Secundus",color:'#c0c0d8',division:'fond4',region:'Le Pilier',tier:'district',house:"Luna",houseColor:'#c0c0d8',branch:"Secundus",level:'dh'},
  {name:"Gloria Nova",color:'#9ad8b0',division:'fond4',region:'Le Pilier',tier:'district',house:"Gloria",houseColor:'#e0c040',branch:"Nova",level:'dh'},
];

function pilierTeamsByDivision(divId){ return PILIER_TEAMS.filter(t=>t.division===divId); }
function pilierHouseClubs(house){ return PILIER_TEAMS.filter(t=>t.house===house); }
if(typeof window!=='undefined'){
  window.PILIER_TEAMS = PILIER_TEAMS;
  window.PILIER_DIVISIONS = PILIER_DIVISIONS;
  window.pilierTeamsByDivision = pilierTeamsByDivision;
  window.pilierHouseClubs = pilierHouseClubs;
}
